{ ... }:

{
  # The suffix (33DDK3) is generated by the desktop environment.
  # It can change across Plasma/GNOME versions. If the file no
  # longer exists, regenerate the entry with the new suffix.
  home.file.".local/share/applications/userapp-transmission-gtk-33DDK3.desktop" = {
    text = ''
      [Desktop Entry]
      Name=userapp-transmission-gtk-33DDK3
      NoDisplay=true
    '';
    force = true;
  };

}
