#!/usr/bin/env bash
last=""
print_layout() {
    data=$(swaymsg -t get_tree | jq -r '
        if ([.. | select(.focused? == true) | select(.type? == "floating_con")] | length) > 0 then "floating" else
          [.. | select(.layout? and .layout != "none" and .layout != "output" and (. | .. | select(.focused? == true))) | .layout][-1]
        end
    ')
    if [ -n "$data" ] && [ "$data" != "null" ]; then
        case "$data" in
            floating) icon="[F]" ;;
            tabbed)   icon="[T]" ;;
            stacking) icon="[S]" ;;
            splith)   icon="[H]" ;;
            splitv)   icon="[V]" ;;
            *)        icon="$last" ;;
        esac
        last="$icon"
    fi
    [ -z "$last" ] && return
    echo "$last"
}
print_layout
swaymsg -t SUBSCRIBE -m '["window","binding","mode","focus"]' | while read -r; do
    print_layout
done
