#!/usr/bin/env bash
vol=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{printf "%.0f", $2 * 100}')
mute=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -c MUTED)
if [ "$mute" -gt 0 ]; then
    echo "Vol: MUTED"
else
    echo "Vol: ${vol}%"
fi
