# Package danfking/ascii-align (npm CLI) — not in nixpkgs (checked 2026-08).
# Detects and fixes misaligned ASCII boxes and Markdown tables generated by
# LLMs, correctly handling wide (CJK/emoji) characters and ANSI codes.
# CLI: `ascii-align check|fix [file]` (exit code 1 when misaligned).
final: prev: {
  ascii-align = prev.buildNpmPackage {
    pname = "ascii-align";
    version = "1.0.4";
    src = prev.fetchFromGitHub {
      owner = "danfking";
      repo = "ascii-align";
      rev = "v1.0.4";
      hash = "sha256-Qv5o47Vg61Iq0yMvQjvm7kpr8nKLBZqr0Qvpf7DvqMk=";
    };
    npmDepsHash = "sha256-dHA3xAU4Jk26B/Fhf4iAB34wtdGM6EGBVGcX+lmSqmE=";
    meta = {
      description = "Fix misaligned ASCII boxes and tables (CJK-aware), for LLM-generated diagrams";
      homepage = "https://github.com/danfking/ascii-align";
      license = prev.lib.licenses.mit;
      mainProgram = "ascii-align";
    };
  };
}
