(define-derived-mode nmcli-wifi-mode tabulated-list-mode
  "nmcli-wifi"
  "nmcli WiFi Mode"
  (let ((columns [("IN-USE" 10 t)
                  ("BSSID" 20 t)
                  ("SSID" 30 t)
                  ("MODE" 10 t)
                  ("CHAN" 5 t)
                  ("RATE" 15 t)
                  ("SIGNAL" 10 t)
                  ("BARS" 5 t)
                  ("SECURITY" 10 t)])
        (rows (nmcli-wifi--shell-command)))
    (setq tabulated-list-format columns)
    (setq tabulated-list-entries rows)
    (tabulated-list-init-header)
    (tabulated-list-print)))

(defun nmcli-wifi-refresh ()
  (interactive)
  (let ((rows (nmcli-wifi--shell-command)))
    (setq tabulated-list-entries rows)
    (tabulated-list-print t t)))

(defun nmcli-wifi--shell-command ()
  (let* ((output (shell-command-to-string "nmcli dev wifi"))
         (lines (cdr (split-string output "\n" t)))
         (entries (make-hash-table :test 'equal)))
    (dolist (line lines)
      (let* ((line (string-trim line))
             (in-use "")
             (rest line))
        (when (string-prefix-p "*" line)
          (setq in-use "*")
          (setq rest (string-trim (substring line 1))))
        (let* ((fields (split-string rest "  " t " "))
               (bssid (nth 0 fields))
               (ssid (nth 1 fields))
               (mode (nth 2 fields))
               (chan (nth 3 fields))
               (rate (nth 4 fields))
               (signal-str (nth 5 fields))
               (bars (nth 6 fields))
               (security (nth 7 fields))
               (signal-num (string-to-number signal-str))
               (ssid (string-trim ssid))
               (current (gethash ssid entries))
               (all-fields (list in-use bssid ssid mode chan rate signal-str bars security)))
          (when (and ssid (not (string= "" ssid)))
            (when (or (null current)
                      (string= in-use "*")
                      (and (not (string= (nth 0 current) "*"))
                           (> signal-num (nth 1 current))))
              (puthash ssid (list in-use signal-num (vconcat all-fields)) entries))))))
    (let (result)
      (maphash (lambda (ssid data)
                 (push `(,ssid ,(nth 2 data)) result))
               entries)
      (sort result (lambda (a b)
                     (> (string-to-number (aref (cadr a) 6))
                        (string-to-number (aref (cadr b) 6))))))))

(defun nmcli-wifi--get-wifi-device ()
  (let ((output (shell-command-to-string "nmcli -t -f DEVICE,TYPE dev")))
    (when (string-match "^\\([^:]+\\):wifi$" output)
      (match-string 1 output))))

(defun nmcli-wifi--sudo-shell-command (cmd)
  (let ((password (read-passwd "sudo password: " t)))
    (unwind-protect
        (shell-command
         (format "printf '%%s\n' %s | sudo -S %s 2>&1"
                 (shell-quote-argument password)
                 cmd))
      (clear-string password))))

(defun nmcli-wifi ()
  (interactive)
  (switch-to-buffer "*nmcli-wifi*")
  (nmcli-wifi-mode))

(defun nmcli-wifi-connect ()
  (interactive)
  (let* ((ssid (tabulated-list-get-id))
         (entry (tabulated-list-get-entry))
         (security (aref entry 8))
         (password-required (not (string= "--" security)))
         (wifi-password (when password-required
                          (read-passwd "WiFi Password: ")))
         (cmd (if password-required
                  (format "nmcli dev wifi connect \"%s\" password \"%s\"" ssid wifi-password)
                (format "nmcli dev wifi connect \"%s\"" ssid))))
    (when wifi-password
      (clear-string wifi-password))
    (nmcli-wifi--sudo-shell-command cmd)
    (nmcli-wifi-refresh)))

(defun nmcli-wifi-disconnect ()
  (interactive)
  (let ((device (nmcli-wifi--get-wifi-device)))
    (if (not device)
        (message "No WiFi device found")
      (nmcli-wifi--sudo-shell-command
       (format "nmcli dev disconnect %s" device))
      (nmcli-wifi-refresh))))

(define-key nmcli-wifi-mode-map (kbd "g") 'nmcli-wifi-refresh)
(define-key nmcli-wifi-mode-map (kbd "c") 'nmcli-wifi-connect)
(define-key nmcli-wifi-mode-map (kbd "d") 'nmcli-wifi-disconnect)

(provide 'nmcli-wifi)
