# Rime default.custom.yaml
# encoding: utf-8
config_version: '2025-02-24'

schema_list:
  - schema: rime_ice

menu:
  page_size: 5

switcher:
  caption: 「方案选单」
  hotkeys:
    - F4
    - Control+grave
    - Control+Shift+grave
  save_options:
    - ascii_punct
    - traditionalization
    - emoji
    - full_shape
    - search_single_char
  fold_options: true
  abbreviate_options: true
  option_list_separator: ' / '

ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Caps_Lock: clear
    Shift_L: commit_code
    Shift_R: noop
    Control_L: noop
    Control_R: noop

# ==================== 标点符号 ====================
punctuator:
  digit_separators: ",.:"
  full_shape:
    ' ' : { commit: '　' }
    ',' : { commit: ， }
    '.' : { commit: 。 }
    '<' : [ 《, 〈, «, ‹ ]
    '>' : [ 》, 〉, », › ]
    '/' : [ ／, ÷ ]
    '?' : { commit: ？ }
    ';' : { commit: ； }
    ':' : { commit: ： }
    '''' : { pair: [ '‘', '’' ] }
    '"' : { pair: [ '“', '”' ] }
    '\' : [ 、, ＼ ]
    '|' : [ ·, ｜, '§', '¦' ]
    '`' : ｀
    '~' : ～
    '!' : { commit: ！ }
    '@' : [ ＠, ☯ ]
    '#' : [ ＃, ⌘ ]
    '%' : [ ％, '°', '℃' ]
    '$' : [ ￥, '$', '€', '£', '¥', '¢', '¤' ]
    '^' : { commit: …… }
    '&' : ＆
    '*' : [ ＊, ·, ・, ×, ※, ❂ ]
    '(' : （
    ')' : ）
    '-' : －
    '_' : ——
    '+' : ＋
    '=' : ＝
    '[' : [ 「, 【, 〔, ［ ]
    ']' : [ 」, 】, 〕, ］ ]
    '{' : [ 『, 〖, ｛ ]
    '}' : [ 』, 〗, ｝ ]
  half_shape:
    ',' : '，'
    '.' : '。'
    '<' : '《'
    '>' : '》'
    '/' : '/'
    '?' : '？'
    ';' : '；'
    ':' : '：'
    '''' : { pair: [ '‘', '’' ] }
    '"' : { pair: [ '“', '”' ] }
    '\' : '、'
    '|' : [ ·, ｜, '§', '¦' ]
    '`' : '`'
    '~' : '~'
    '!' : '！'
    '@' : '@'
    '#' : '#'
    '%' : '%'
    '$' : '¥'
    '^' : '……'
    '&' : '&'
    '*' : '*'
    '(' : '（'
    ')' : '）'
    '-' : '-'
    '_' : ——
    '+' : '+'
    '=' : '='
    '[' : '【'
    ']' : '】'
    '{' : '「'
    '}' : '」'

# ==================== 识别器 ====================
recognizer:
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"
    underscore: "^[A-Za-z]+_.*"

key_binder:
  bindings:
    - { when: has_menu, accept: Control+bracketleft,  send: Left }
    - { when: has_menu, accept: Control+bracketright, send: Right }

    - { when: has_menu, accept: bracketleft,  send: Page_Up }
    - { when: has_menu, accept: bracketright, send: Page_Down }
    
    # ── 拼音内光标移动 ──
    - { when: composing, accept: Tab,        send: Shift+Right }
    - { when: composing, accept: Shift+Tab,  send: Shift+Left }
    - { when: composing, accept: Alt+Left,   send: Shift+Left }
    - { when: composing, accept: Alt+Right,  send: Shift+Right }

    # ── 功能切换 ──
    - { when: always, toggle: ascii_punct,        accept: Control+Shift+3 }
    - { when: always, toggle: ascii_punct,        accept: Control+Shift+numbersign }
    - { when: always, toggle: traditionalization, accept: Control+Shift+4 }
    - { when: always, toggle: traditionalization, accept: Control+Shift+dollar }

    # ── 小键盘映射 ──
    - {accept: KP_0, send: 0, when: composing}
    - {accept: KP_1, send: 1, when: composing}
    - {accept: KP_2, send: 2, when: composing}
    - {accept: KP_3, send: 3, when: composing}
    - {accept: KP_4, send: 4, when: composing}
    - {accept: KP_5, send: 5, when: composing}
    - {accept: KP_6, send: 6, when: composing}
    - {accept: KP_7, send: 7, when: composing}
    - {accept: KP_8, send: 8, when: composing}
    - {accept: KP_9, send: 9, when: composing}
    - {accept: KP_Decimal, send: period, when: composing}
    - {accept: KP_Multiply, send: asterisk, when: composing}
    - {accept: KP_Add, send: plus, when: composing}
    - {accept: KP_Subtract, send: minus, when: composing}
    - {accept: KP_Divide, send: slash, when: composing}
